"""
Seed data for interests — 1000+ interests across 20 categories.
Run via: python -m app.seed_interests  (or called from main.py on startup)
"""
from database import SessionLocal
from app.models import Interest


INTERESTS_BY_CATEGORY = {
    "Technology": [
        ("Artificial Intelligence", "🤖"), ("Machine Learning", "🧠"), ("Web Development", "🌐"),
        ("Mobile Apps", "📱"), ("Cybersecurity", "🔒"), ("Blockchain", "⛓️"), ("Cloud Computing", "☁️"),
        ("Data Science", "📊"), ("DevOps", "⚙️"), ("Open Source", "💻"), ("Robotics", "🦾"),
        ("Virtual Reality", "🥽"), ("Augmented Reality", "👓"), ("3D Printing", "🖨️"),
        ("Internet of Things", "📡"), ("Quantum Computing", "⚛️"), ("Programming", "👨‍💻"),
        ("Python", "🐍"), ("JavaScript", "📜"), ("Rust", "🦀"), ("Linux", "🐧"),
        ("Databases", "🗄️"), ("APIs", "🔗"), ("Game Development", "🕹️"), ("UI/UX Design", "🎨"),
        ("Startups", "🚀"), ("Tech News", "📰"), ("Hacking", "🏴‍☠️"), ("Drones", "🛸"),
        ("Smart Home", "🏠"), ("Wearable Tech", "⌚"), ("SaaS", "💡"), ("No-Code", "🧩"),
        ("Computer Vision", "👁️"), ("NLP", "💬"), ("Edge Computing", "📲"),
        ("Digital Privacy", "🛡️"), ("5G", "📶"), ("Semiconductors", "🔌"), ("Tech Ethics", "⚖️"),
        ("Space Tech", "🛰️"), ("Biotech", "🧬"), ("FinTech", "💳"), ("EdTech", "📚"),
        ("Green Tech", "🌱"), ("Hardware", "🔧"), ("Networking", "🌐"), ("Automation", "🤖"),
        ("Software Engineering", "🏗️"), ("Agile", "🔄"),
    ],
    "Music": [
        ("Pop Music", "🎵"), ("Rock", "🎸"), ("Hip Hop", "🎤"), ("R&B", "🎶"),
        ("Jazz", "🎷"), ("Classical", "🎻"), ("Electronic", "🎧"), ("EDM", "💿"),
        ("Country", "🤠"), ("Blues", "🎺"), ("Reggae", "🇯🇲"), ("Punk", "🤘"),
        ("Metal", "🎸"), ("Folk", "🪕"), ("Soul", "❤️"), ("Indie", "🎹"),
        ("K-Pop", "🇰🇷"), ("Latin Music", "💃"), ("Afrobeats", "🥁"), ("Lo-fi", "😴"),
        ("Synthwave", "🌆"), ("Ambient", "🌊"), ("Acoustic", "🎵"), ("Gospel", "🙏"),
        ("Opera", "🎭"), ("DJ / Mixing", "🎛️"), ("Music Production", "🎚️"),
        ("Singing", "🎤"), ("Songwriting", "✍️"), ("Guitar", "🎸"), ("Piano", "🎹"),
        ("Drums", "🥁"), ("Vinyl / Records", "📀"), ("Music Theory", "📝"),
        ("Concert Going", "🎪"), ("Music History", "📖"), ("Film Scores", "🎬"),
        ("Podcasts", "🎙️"), ("Music Videos", "📺"), ("Karaoke", "🎤"),
        ("Band", "🎵"), ("Orchestra", "🎻"), ("Music Festivals", "🎪"),
        ("Audio Engineering", "🔊"), ("Beat Making", "🥁"), ("Rap", "🎤"),
        ("Trap", "🔥"), ("Drill", "💀"), ("Chill Music", "🧊"), ("Workout Music", "💪"),
    ],
    "Sports": [
        ("Football / Soccer", "⚽"), ("Basketball", "🏀"), ("Tennis", "🎾"),
        ("Cricket", "🏏"), ("Baseball", "⚾"), ("Swimming", "🏊"), ("Running", "🏃"),
        ("Cycling", "🚴"), ("Golf", "⛳"), ("Boxing", "🥊"), ("MMA", "🥋"),
        ("Wrestling", "🤼"), ("Volleyball", "🏐"), ("Badminton", "🏸"),
        ("Table Tennis", "🏓"), ("Skateboarding", "🛹"), ("Surfing", "🏄"),
        ("Snowboarding", "🏂"), ("Skiing", "⛷️"), ("Rock Climbing", "🧗"),
        ("Hiking", "🥾"), ("Martial Arts", "🥷"), ("Yoga", "🧘"), ("Pilates", "🧘‍♀️"),
        ("CrossFit", "🏋️"), ("Weightlifting", "💪"), ("Formula 1", "🏎️"),
        ("Horse Riding", "🏇"), ("Archery", "🏹"), ("Fencing", "🤺"),
        ("Track & Field", "🏅"), ("Rugby", "🏉"), ("Hockey", "🏒"),
        ("American Football", "🏈"), ("Handball", "🤾"), ("Water Polo", "🤽"),
        ("Rowing", "🚣"), ("Sailing", "⛵"), ("Kayaking", "🛶"), ("Scuba Diving", "🤿"),
        ("Triathlon", "🏊‍♂️"), ("Gymnastics", "🤸"), ("Ice Skating", "⛸️"),
        ("Parkour", "🧗"), ("Esports", "🎮"), ("Chess", "♟️"), ("Fishing", "🎣"),
        ("Bowling", "🎳"), ("Darts", "🎯"), ("Lacrosse", "🥍"),
    ],
    "Gaming": [
        ("PC Gaming", "🖥️"), ("Console Gaming", "🎮"), ("Mobile Gaming", "📱"),
        ("RPG", "⚔️"), ("FPS", "🔫"), ("MMORPG", "🌍"), ("Strategy Games", "🧠"),
        ("Puzzle Games", "🧩"), ("Indie Games", "🎮"), ("Retro Gaming", "👾"),
        ("Minecraft", "⛏️"), ("Fortnite", "🏗️"), ("League of Legends", "🏆"),
        ("Valorant", "💎"), ("CS2", "🔫"), ("Apex Legends", "🌟"), ("GTA", "🚗"),
        ("Call of Duty", "🎖️"), ("FIFA / EA Sports FC", "⚽"), ("Pokemon", "🐾"),
        ("Nintendo", "🍄"), ("PlayStation", "🎮"), ("Xbox", "🟢"),
        ("Game Streaming", "📺"), ("Speedrunning", "⏱️"), ("Modding", "🔧"),
        ("Board Games", "🎲"), ("Card Games", "🃏"), ("Tabletop RPG", "🐉"),
        ("Game Design", "🎨"), ("VR Gaming", "🥽"), ("Simulation Games", "🛩️"),
        ("Horror Games", "👻"), ("Racing Games", "🏎️"), ("Fighting Games", "🥊"),
        ("Survival Games", "🏕️"), ("Open World", "🗺️"), ("Co-op Gaming", "🤝"),
        ("Competitive Gaming", "🏆"), ("Game Lore", "📜"), ("Roblox", "🧱"),
        ("Genshin Impact", "✨"), ("Elden Ring", "💍"), ("Zelda", "🗡️"),
        ("Animal Crossing", "🏝️"), ("Stardew Valley", "🌾"), ("Souls-like", "💀"),
        ("Roguelike", "🎲"), ("City Builders", "🏙️"), ("Tower Defense", "🏰"),
    ],
    "Art & Design": [
        ("Digital Art", "🎨"), ("Illustration", "✏️"), ("Graphic Design", "🖌️"),
        ("Animation", "🎬"), ("Painting", "🖼️"), ("Sculpture", "🗿"),
        ("Typography", "🔤"), ("Calligraphy", "✒️"), ("Street Art", "🏙️"),
        ("Graffiti", "🎨"), ("Tattoo Art", "💉"), ("Pixel Art", "👾"),
        ("Concept Art", "🎭"), ("Character Design", "🧑‍🎨"), ("Logo Design", "💫"),
        ("Interior Design", "🛋️"), ("Architecture", "🏛️"), ("Fashion Design", "👗"),
        ("Industrial Design", "🏭"), ("Web Design", "🌐"), ("Motion Graphics", "🎞️"),
        ("3D Modeling", "🧊"), ("Ceramics", "🏺"), ("Pottery", "🫖"),
        ("Woodworking", "🪵"), ("Jewelry Making", "💎"), ("Print Making", "🖨️"),
        ("Collage Art", "📎"), ("Abstract Art", "🔶"), ("Watercolor", "💧"),
        ("Oil Painting", "🎨"), ("Sketch Art", "📝"), ("Comic Art", "💥"),
        ("Manga Art", "📖"), ("Photography Art", "📸"), ("Mixed Media", "🎭"),
        ("Art History", "🏛️"), ("Art Criticism", "📰"), ("Gallery Exhibitions", "🖼️"),
        ("NFT Art", "🖼️"), ("Generative Art", "🤖"), ("Fiber Arts", "🧶"),
        ("Stained Glass", "🪟"), ("Mosaics", "🧩"), ("Basket Weaving", "🧺"),
        ("Paper Crafts", "📄"), ("Origami", "🦢"), ("Quilling", "🌸"),
        ("Resin Art", "✨"), ("Metal Art", "⚒️"),
    ],
    "Movies & TV": [
        ("Action Movies", "💥"), ("Comedy Movies", "😂"), ("Drama", "🎭"),
        ("Horror Movies", "👻"), ("Sci-Fi", "🚀"), ("Fantasy", "🧙"),
        ("Thriller", "😱"), ("Romance", "💕"), ("Documentary", "📹"),
        ("Animation", "🎬"), ("Anime", "🇯🇵"), ("K-Drama", "🇰🇷"),
        ("Bollywood", "🇮🇳"), ("Marvel / MCU", "🦸"), ("DC Comics", "🦇"),
        ("Star Wars", "⭐"), ("Lord of the Rings", "💍"), ("Harry Potter", "🧙"),
        ("Netflix", "📺"), ("Sitcoms", "😄"), ("True Crime", "🔍"),
        ("Reality TV", "📷"), ("Film Noir", "🎬"), ("Indie Films", "🎥"),
        ("Classic Movies", "🎞️"), ("Foreign Films", "🌍"), ("Film Criticism", "✍️"),
        ("Screenwriting", "📝"), ("Directing", "🎬"), ("Cinematography", "📽️"),
        ("Film Festivals", "🏆"), ("Short Films", "🎞️"), ("TV Series", "📺"),
        ("Miniseries", "📺"), ("Stand-up Comedy", "🎤"), ("Webseries", "💻"),
        ("Movie Reviews", "⭐"), ("Oscar Talk", "🏆"), ("B-Movies", "🎬"),
        ("Musical Films", "🎶"), ("War Movies", "⚔️"), ("Westerns", "🤠"),
        ("Cult Classics", "🕶️"), ("Superhero Movies", "🦸"), ("Stop Motion", "🧸"),
        ("Noir", "🌑"), ("Coming of Age", "🎒"), ("Biopics", "📖"),
        ("Period Dramas", "👑"), ("Mockumentary", "🎥"),
    ],
    "Books & Literature": [
        ("Fiction", "📖"), ("Non-Fiction", "📚"), ("Science Fiction", "🚀"),
        ("Fantasy Books", "🐉"), ("Mystery", "🔍"), ("Thriller Books", "😰"),
        ("Romance Novels", "💝"), ("Historical Fiction", "⏳"), ("Biography", "👤"),
        ("Memoir", "📝"), ("Self-Help", "🌟"), ("Philosophy", "🤔"),
        ("Poetry", "🖊️"), ("Short Stories", "📃"), ("Young Adult", "🎒"),
        ("Children's Books", "🧒"), ("Graphic Novels", "💥"), ("Comics", "📰"),
        ("Manga", "🇯🇵"), ("Light Novels", "📖"), ("Classic Literature", "📜"),
        ("Horror Books", "👻"), ("Dystopian", "🏚️"), ("Crime Fiction", "🔫"),
        ("Psychological Thriller", "🧠"), ("Literary Fiction", "🖋️"),
        ("Book Clubs", "📚"), ("Audiobooks", "🎧"), ("E-Books", "📱"),
        ("Writing", "✍️"), ("Creative Writing", "📝"), ("Journalism", "📰"),
        ("Blogging", "💻"), ("Editing", "✂️"), ("Publishing", "📕"),
        ("Essay Writing", "📄"), ("Satire", "😏"), ("Political Fiction", "🏛️"),
        ("Magical Realism", "✨"), ("Urban Fantasy", "🌆"), ("Epic Fantasy", "⚔️"),
        ("Hard Sci-Fi", "🔬"), ("Space Opera", "🌌"), ("Cyberpunk", "🤖"),
        ("Steampunk", "⚙️"), ("Gothic", "🏰"), ("Adventure", "🗺️"),
        ("Dark Fantasy", "🌑"), ("Mythology", "🏛️"), ("Folklore", "🧚"),
    ],
    "Food & Cooking": [
        ("Cooking", "👨‍🍳"), ("Baking", "🍰"), ("BBQ / Grilling", "🔥"),
        ("Vegan Cooking", "🥗"), ("Vegetarian", "🥦"), ("Italian Food", "🍝"),
        ("Mexican Food", "🌮"), ("Japanese Food", "🍣"), ("Korean Food", "🍜"),
        ("Indian Food", "🍛"), ("Thai Food", "🍜"), ("Chinese Food", "🥡"),
        ("Mediterranean", "🫒"), ("French Cuisine", "🥐"), ("Middle Eastern", "🧆"),
        ("American BBQ", "🥩"), ("Seafood", "🦐"), ("Desserts", "🍫"),
        ("Bread Making", "🍞"), ("Pastry", "🧁"), ("Pizza", "🍕"),
        ("Sushi", "🍱"), ("Coffee", "☕"), ("Tea", "🍵"), ("Wine", "🍷"),
        ("Craft Beer", "🍺"), ("Cocktails", "🍹"), ("Smoothies", "🥤"),
        ("Meal Prep", "📦"), ("Street Food", "🥙"), ("Food Photography", "📸"),
        ("Food Blogging", "📝"), ("Restaurant Reviews", "⭐"), ("Fermentation", "🫙"),
        ("Pickling", "🥒"), ("Canning", "🥫"), ("Cheese Making", "🧀"),
        ("Chocolate", "🍫"), ("Ice Cream", "🍦"), ("Farmers Markets", "🌽"),
        ("Organic Food", "🌿"), ("Keto Diet", "🥑"), ("Paleo", "🦴"),
        ("Intermittent Fasting", "⏰"), ("Nutrition", "🍎"), ("Food Science", "🔬"),
        ("Spices & Herbs", "🌶️"), ("Comfort Food", "🥘"), ("Soup", "🍲"),
        ("Noodles", "🍜"),
    ],
    "Travel": [
        ("Backpacking", "🎒"), ("Solo Travel", "🧳"), ("Road Trips", "🚗"),
        ("Beach Travel", "🏖️"), ("Mountain Travel", "🏔️"), ("City Breaks", "🏙️"),
        ("Luxury Travel", "✨"), ("Budget Travel", "💰"), ("Adventure Travel", "🧗"),
        ("Cultural Travel", "🏛️"), ("Eco Travel", "🌿"), ("Digital Nomad", "💻"),
        ("Van Life", "🚐"), ("Camping", "⛺"), ("Hostels", "🛏️"),
        ("Europe Travel", "🇪🇺"), ("Asia Travel", "🌏"), ("Africa Travel", "🌍"),
        ("South America", "🌎"), ("North America", "🌎"), ("Australia", "🦘"),
        ("Japan Travel", "🇯🇵"), ("Italy Travel", "🇮🇹"), ("Thailand Travel", "🇹🇭"),
        ("India Travel", "🇮🇳"), ("Travel Photography", "📷"), ("Travel Blogging", "✍️"),
        ("Travel Vlogging", "📹"), ("Islands", "🏝️"), ("Wildlife Safaris", "🦁"),
        ("Cruises", "🚢"), ("Train Travel", "🚂"), ("Flights", "✈️"),
        ("Travel Hacking", "💳"), ("Volunteering Abroad", "🤝"), ("Study Abroad", "📚"),
        ("Expat Life", "🌍"), ("Food Travel", "🍽️"), ("Historical Sites", "🏰"),
        ("National Parks", "🌲"), ("World Heritage", "🏛️"), ("Pilgrimage", "🙏"),
        ("Festivals Abroad", "🎪"), ("Desert Travel", "🏜️"), ("Arctic Travel", "🧊"),
        ("Scuba Travel", "🤿"), ("Ski Resorts", "⛷️"), ("Spa / Wellness", "🧖"),
        ("Photography Tours", "📸"), ("Heritage Walks", "🚶"),
    ],
    "Science": [
        ("Physics", "⚛️"), ("Biology", "🧬"), ("Chemistry", "🧪"),
        ("Astronomy", "🔭"), ("Neuroscience", "🧠"), ("Psychology", "🧠"),
        ("Mathematics", "🔢"), ("Statistics", "📊"), ("Environmental Science", "🌍"),
        ("Geology", "🪨"), ("Oceanography", "🌊"), ("Meteorology", "🌤️"),
        ("Paleontology", "🦕"), ("Archaeology", "🏺"), ("Anthropology", "👤"),
        ("Genetics", "🧬"), ("Virology", "🦠"), ("Immunology", "💉"),
        ("Pharmacology", "💊"), ("Ecology", "🌿"), ("Marine Biology", "🐬"),
        ("Botany", "🌱"), ("Zoology", "🦁"), ("Astrophysics", "🌌"),
        ("Cosmology", "🌀"), ("Particle Physics", "⚛️"), ("Climate Science", "🌡️"),
        ("Renewable Energy", "☀️"), ("Nuclear Science", "☢️"), ("Space Exploration", "🚀"),
        ("NASA", "🛰️"), ("SpaceX", "🚀"), ("Research", "🔬"),
        ("Scientific Method", "📋"), ("STEM Education", "🎓"), ("Science News", "📰"),
        ("Evolution", "🐒"), ("Taxonomy", "📂"), ("Bioinformatics", "💻"),
        ("Forensic Science", "🔍"), ("Materials Science", "🧱"), ("Nanotechnology", "🔬"),
        ("Optics", "🔦"), ("Acoustics", "🔊"), ("Thermodynamics", "🌡️"),
        ("Electromagnetism", "⚡"), ("Fluid Dynamics", "💧"), ("Chaos Theory", "🌀"),
        ("Game Theory", "🎯"), ("Cryptography", "🔐"),
    ],
    "Fashion": [
        ("Streetwear", "👟"), ("High Fashion", "👗"), ("Vintage Fashion", "🕰️"),
        ("Sustainable Fashion", "♻️"), ("Men's Fashion", "👔"), ("Women's Fashion", "👠"),
        ("Sneakers", "👟"), ("Watches", "⌚"), ("Jewelry", "💍"),
        ("Bags & Accessories", "👜"), ("Makeup", "💄"), ("Skincare", "🧴"),
        ("Haircare", "💇"), ("Nail Art", "💅"), ("Perfume", "🌸"),
        ("Thrifting", "🛍️"), ("Fashion Design", "✂️"), ("Modeling", "📸"),
        ("Fashion Photography", "📷"), ("Fashion Blogging", "✍️"), ("Y2K Fashion", "🦋"),
        ("Minimalist Fashion", "⬜"), ("Athleisure", "🧘"), ("Workwear", "👔"),
        ("Capsule Wardrobe", "📦"), ("Fashion Week", "🏙️"), ("Luxury Brands", "💎"),
        ("Denim", "👖"), ("Leather", "🧥"), ("Knitwear", "🧣"),
        ("Color Theory", "🌈"), ("Pattern Making", "📐"), ("Tailoring", "🪡"),
        ("Costume Design", "🎭"), ("Cosplay", "🦸"), ("Upcycling", "🔄"),
        ("Plus Size Fashion", "👗"), ("Kids Fashion", "👶"), ("Bridal Fashion", "👰"),
        ("Gothic Fashion", "🖤"), ("Bohemian Style", "🌻"), ("Preppy Style", "🎓"),
        ("Korean Fashion", "🇰🇷"), ("Japanese Fashion", "🇯🇵"),
        ("Fashion Tech", "💻"), ("Eyewear", "👓"), ("Hats", "🎩"),
        ("Shoes", "👠"), ("Fit Checks", "📸"), ("OOTD", "🪞"),
    ],
    "Health & Fitness": [
        ("Gym", "🏋️"), ("Home Workouts", "🏠"), ("Cardio", "🏃"),
        ("Strength Training", "💪"), ("HIIT", "🔥"), ("Bodybuilding", "🏋️"),
        ("Calisthenics", "🤸"), ("Stretching", "🧘"), ("Meditation", "🧘"),
        ("Mental Health", "🧠"), ("Therapy", "💚"), ("Mindfulness", "🙏"),
        ("Sleep Health", "😴"), ("Nutrition", "🥗"), ("Supplements", "💊"),
        ("Weight Loss", "⚖️"), ("Muscle Gain", "💪"), ("Marathon Training", "🏃"),
        ("Triathlon Training", "🏊"), ("Personal Training", "🏋️"), ("Group Fitness", "👥"),
        ("Spin / Indoor Cycling", "🚴"), ("Dance Fitness", "💃"), ("Barre", "🩰"),
        ("Boxing Fitness", "🥊"), ("Functional Training", "🧱"), ("Mobility", "🦿"),
        ("Posture", "🧍"), ("Physical Therapy", "🩹"), ("Recovery", "🧊"),
        ("Foam Rolling", "🧘"), ("Cold Plunge", "🧊"), ("Sauna", "🧖"),
        ("Wellness", "🌿"), ("Holistic Health", "🌸"), ("Ayurveda", "🌿"),
        ("TCM", "🇨🇳"), ("Herbal Medicine", "🌿"), ("Acupuncture", "📍"),
        ("Breathwork", "🌬️"), ("Gratitude Practice", "🙏"), ("Journaling", "📓"),
        ("Stress Management", "😤"), ("Work-Life Balance", "⚖️"),
        ("Digital Detox", "📵"), ("Self-Care", "🛁"), ("Habit Building", "📋"),
        ("Biohacking", "🧬"), ("Longevity", "⏳"), ("Wim Hof Method", "🧊"),
    ],
    "Photography": [
        ("Portrait Photography", "👤"), ("Landscape Photography", "🏞️"),
        ("Street Photography", "🏙️"), ("Wildlife Photography", "🦁"),
        ("Macro Photography", "🔬"), ("Night Photography", "🌃"),
        ("Astrophotography", "🌌"), ("Food Photography", "🍽️"),
        ("Fashion Photography", "📸"), ("Wedding Photography", "💒"),
        ("Travel Photography", "✈️"), ("Documentary Photography", "📹"),
        ("Film Photography", "🎞️"), ("Black & White", "⬛"),
        ("Drone Photography", "🛸"), ("Underwater Photography", "🤿"),
        ("Sports Photography", "🏃"), ("Architecture Photography", "🏛️"),
        ("Product Photography", "📦"), ("Event Photography", "🎪"),
        ("Mobile Photography", "📱"), ("Photo Editing", "🎨"),
        ("Lightroom", "📷"), ("Photoshop", "🖌️"), ("Camera Gear", "📷"),
        ("Lenses", "🔭"), ("Lighting", "💡"), ("Composition", "📐"),
        ("Color Grading", "🎨"), ("HDR Photography", "🌅"),
        ("Long Exposure", "⏱️"), ("Timelapse", "🎥"), ("Panorama", "🌄"),
        ("Candid Photography", "📸"), ("Self-Portraits", "🤳"),
        ("Pet Photography", "🐕"), ("Newborn Photography", "👶"),
        ("Surreal Photography", "🎭"), ("Abstract Photography", "🔶"),
        ("Analog Photography", "📸"), ("Photo Walks", "🚶"),
        ("Photography Education", "📚"), ("Photo Books", "📖"),
        ("Exhibitions", "🖼️"), ("Stock Photography", "📁"),
        ("Photography Business", "💼"), ("Creative Photography", "✨"),
        ("Double Exposure", "👁️"), ("Infrared Photography", "🔴"), ("Toy Photography", "🧸"),
    ],
    "Nature & Outdoors": [
        ("Hiking", "🥾"), ("Camping", "⛺"), ("Mountain Climbing", "🏔️"),
        ("Bird Watching", "🐦"), ("Gardening", "🌻"), ("Fishing", "🎣"),
        ("Foraging", "🍄"), ("Star Gazing", "✨"), ("National Parks", "🌲"),
        ("Wilderness Survival", "🏕️"), ("Trail Running", "🏃"), ("Canoeing", "🛶"),
        ("Kayaking", "🚣"), ("Rock Climbing", "🧗"), ("Geocaching", "📍"),
        ("Orienteering", "🧭"), ("Nature Photography", "📸"), ("Botany", "🌱"),
        ("Entomology", "🦋"), ("Weather Watching", "🌦️"), ("Beach Life", "🏖️"),
        ("Forest Bathing", "🌳"), ("Tree Identification", "🌲"), ("Mushroom Hunting", "🍄"),
        ("Flower Arranging", "💐"), ("Landscape Design", "🏡"), ("Permaculture", "🌱"),
        ("Organic Gardening", "🥬"), ("Indoor Plants", "🪴"), ("Succulents", "🌵"),
        ("Bonsai", "🌳"), ("Aquascaping", "🐠"), ("Terrarium", "🫙"),
        ("Composting", "♻️"), ("Beekeeping", "🐝"), ("Butterfly Gardening", "🦋"),
        ("Herb Growing", "🌿"), ("Fruit Trees", "🍎"), ("Vegetable Garden", "🥕"),
        ("Conservation", "🌍"), ("Environmental Activism", "✊"), ("Wildlife Rescue", "🦉"),
        ("Marine Conservation", "🐋"), ("Reforestation", "🌲"), ("Eco-Living", "🏡"),
        ("Off-Grid Living", "🏕️"), ("Homesteading", "🏠"), ("Rainwater Harvesting", "🌧️"),
        ("Solar Energy", "☀️"), ("Sustainable Living", "♻️"),
    ],
    "Business & Finance": [
        ("Entrepreneurship", "🚀"), ("Investing", "📈"), ("Stock Market", "💹"),
        ("Cryptocurrency", "₿"), ("Real Estate", "🏠"), ("Personal Finance", "💰"),
        ("Marketing", "📣"), ("Digital Marketing", "📱"), ("SEO", "🔍"),
        ("Content Marketing", "📝"), ("Social Media Marketing", "📲"),
        ("Email Marketing", "📧"), ("Branding", "™️"), ("Sales", "🤝"),
        ("E-Commerce", "🛒"), ("Dropshipping", "📦"), ("Amazon FBA", "📦"),
        ("Side Hustles", "💡"), ("Freelancing", "👨‍💻"), ("Consulting", "💼"),
        ("Leadership", "👑"), ("Management", "📊"), ("HR", "👥"),
        ("Accounting", "🧮"), ("Taxes", "📋"), ("Financial Planning", "📊"),
        ("Retirement Planning", "🏖️"), ("Passive Income", "💸"),
        ("Venture Capital", "💰"), ("Angel Investing", "😇"), ("IPO", "🔔"),
        ("Day Trading", "📉"), ("Options Trading", "📊"), ("Forex", "💱"),
        ("NFTs", "🖼️"), ("DeFi", "🏦"), ("Web3", "🌐"),
        ("Business Strategy", "♟️"), ("Operations", "⚙️"), ("Supply Chain", "🔗"),
        ("Logistics", "🚚"), ("Product Management", "📦"), ("Project Management", "📋"),
        ("Negotiation", "🤝"), ("Public Speaking", "🎤"), ("Networking", "🤝"),
        ("Business Books", "📚"), ("MBA", "🎓"), ("Lean Startup", "🏃"),
        ("Growth Hacking", "📈"),
    ],
    "Education": [
        ("Online Learning", "💻"), ("Teaching", "👩‍🏫"), ("Tutoring", "📝"),
        ("STEM", "🔬"), ("Coding Bootcamps", "💻"), ("Language Learning", "🗣️"),
        ("Study Tips", "📚"), ("Research", "🔍"), ("Academic Writing", "✍️"),
        ("Scholarships", "🎓"), ("College Life", "🏫"), ("Graduate School", "📖"),
        ("PhD Life", "🎓"), ("Study Abroad", "✈️"), ("Homeschooling", "🏠"),
        ("Montessori", "🧸"), ("Special Education", "💚"), ("Gifted Education", "🌟"),
        ("Early Childhood", "👶"), ("High School", "🏫"), ("University", "🎓"),
        ("Distance Learning", "🌐"), ("MOOCs", "📺"), ("Coursera", "🎓"),
        ("Khan Academy", "📚"), ("EdTech", "💡"), ("Curriculum Design", "📋"),
        ("Assessment", "📝"), ("Pedagogy", "📖"), ("Classroom Management", "🏫"),
        ("Student Life", "🎒"), ("Library Science", "📚"), ("Data Literacy", "📊"),
        ("Media Literacy", "📺"), ("Financial Literacy", "💰"),
        ("Digital Literacy", "💻"), ("Critical Thinking", "🤔"),
        ("Problem Solving", "🧩"), ("Lifelong Learning", "🌱"),
        ("Skill Development", "📈"), ("Certification", "📜"), ("Professional Dev", "💼"),
        ("Workshops", "🛠️"), ("Seminars", "🎤"), ("Conferences", "🏢"),
        ("TED Talks", "🎤"), ("Documentaries", "🎬"), ("Open Education", "🌍"),
        ("Knowledge Sharing", "🤝"), ("Mentoring", "👤"),
    ],
    "Languages": [
        ("English", "🇬🇧"), ("Spanish", "🇪🇸"), ("French", "🇫🇷"),
        ("German", "🇩🇪"), ("Japanese", "🇯🇵"), ("Korean", "🇰🇷"),
        ("Chinese / Mandarin", "🇨🇳"), ("Hindi", "🇮🇳"), ("Arabic", "🇸🇦"),
        ("Portuguese", "🇧🇷"), ("Italian", "🇮🇹"), ("Russian", "🇷🇺"),
        ("Turkish", "🇹🇷"), ("Dutch", "🇳🇱"), ("Swedish", "🇸🇪"),
        ("Polish", "🇵🇱"), ("Thai", "🇹🇭"), ("Vietnamese", "🇻🇳"),
        ("Indonesian", "🇮🇩"), ("Tagalog", "🇵🇭"), ("Swahili", "🇰🇪"),
        ("Greek", "🇬🇷"), ("Czech", "🇨🇿"), ("Hebrew", "🇮🇱"),
        ("Latin", "🏛️"), ("Sign Language", "🤟"), ("Esperanto", "🌍"),
        ("Linguistics", "🔤"), ("Etymology", "📖"), ("Translation", "🔄"),
        ("Interpretation", "🎙️"), ("Duolingo", "🦉"), ("Language Exchange", "🤝"),
        ("Polyglot", "🌍"), ("Accent Training", "🗣️"), ("Grammar", "📝"),
        ("Vocabulary Building", "📚"), ("Reading Practice", "📖"),
        ("Listening Practice", "🎧"), ("Speaking Practice", "🗣️"),
        ("Writing Practice", "✍️"), ("Flashcards", "🃏"), ("Anki", "📇"),
        ("Immersion", "🌏"), ("Language Apps", "📱"), ("Textbooks", "📚"),
        ("Native Content", "📺"), ("Subtitles", "📝"), ("Penpal", "✉️"),
        ("Cultural Exchange", "🌍"),
    ],
    "Pets & Animals": [
        ("Dogs", "🐕"), ("Cats", "🐱"), ("Fish", "🐠"),
        ("Birds", "🐦"), ("Hamsters", "🐹"), ("Rabbits", "🐰"),
        ("Reptiles", "🦎"), ("Snakes", "🐍"), ("Turtles", "🐢"),
        ("Guinea Pigs", "🐹"), ("Ferrets", "🦦"), ("Horses", "🐴"),
        ("Pet Care", "❤️"), ("Dog Training", "🦮"), ("Cat Behavior", "😺"),
        ("Aquariums", "🐟"), ("Exotic Pets", "🦜"), ("Pet Photography", "📸"),
        ("Veterinary", "🏥"), ("Animal Rescue", "🦮"), ("Adoption", "❤️"),
        ("Pet Grooming", "✂️"), ("Pet Fashion", "👔"), ("Pet Food", "🍗"),
        ("Dog Parks", "🌳"), ("Cat Cafes", "☕"), ("Animal Welfare", "🐾"),
        ("Wildlife", "🦁"), ("Zoo Visits", "🦒"), ("Sanctuary Visits", "🐘"),
        ("Farm Animals", "🐄"), ("Chickens", "🐔"), ("Goats", "🐐"),
        ("Pig Lovers", "🐷"), ("Insect Keeping", "🦗"), ("Spider Keeping", "🕷️"),
        ("Hedgehogs", "🦔"), ("Sugar Gliders", "🐿️"), ("Chinchillas", "🐭"),
        ("Parrots", "🦜"), ("Canaries", "🐥"), ("Animal Communication", "🗣️"),
        ("Pet Sitting", "🏠"), ("Dog Walking", "🚶"), ("Agility Training", "🏃"),
        ("Therapy Animals", "🐕‍🦺"), ("Service Dogs", "🦮"),
        ("Marine Animals", "🐋"), ("Endangered Species", "🦏"), ("Conservation", "🌍"),
    ],
    "Automotive": [
        ("Cars", "🚗"), ("Electric Vehicles", "⚡"), ("Tesla", "🔋"),
        ("Motorcycles", "🏍️"), ("Classic Cars", "🚘"), ("Car Modification", "🔧"),
        ("Racing", "🏎️"), ("Off-Roading", "🚙"), ("Auto Detailing", "✨"),
        ("Car Photography", "📸"), ("Automotive Design", "✏️"), ("Truck Life", "🚛"),
        ("JDM", "🇯🇵"), ("European Cars", "🇪🇺"), ("American Muscle", "🇺🇸"),
        ("Supercars", "🏎️"), ("Hypercars", "💨"), ("SUVs", "🚙"),
        ("Car Audio", "🔊"), ("Car Tech", "💻"), ("Self-Driving", "🤖"),
        ("Mechanics", "🔧"), ("DIY Repairs", "🛠️"), ("Oil Changes", "🛢️"),
        ("Tires", "🛞"), ("Drag Racing", "🏁"), ("Drifting", "🏎️"),
        ("Rally", "🏎️"), ("NASCAR", "🏁"), ("F1", "🏎️"),
        ("MotoGP", "🏍️"), ("Karting", "🏎️"), ("Car Shows", "🚗"),
        ("Dealerships", "🏢"), ("Car Buying Tips", "💰"), ("Insurance", "📋"),
        ("Road Trips", "🛣️"), ("Car Reviews", "📺"), ("Car Vlogs", "📹"),
        ("Diesel", "⛽"), ("Hybrid Cars", "🔋"), ("Hydrogen Cars", "💧"),
        ("Car History", "📖"), ("Concept Cars", "🔮"), ("Camper Vans", "🚐"),
        ("RV Life", "🏕️"), ("Boat Life", "🚤"), ("ATVs", "🏍️"),
        ("Scooters", "🛵"), ("Bicycles", "🚲"),
    ],
    "DIY & Crafts": [
        ("Woodworking", "🪵"), ("Knitting", "🧶"), ("Crochet", "🧵"),
        ("Sewing", "🪡"), ("Embroidery", "🧵"), ("Cross Stitch", "✂️"),
        ("Quilting", "🛏️"), ("Candle Making", "🕯️"), ("Soap Making", "🧼"),
        ("Resin Crafts", "✨"), ("Jewelry Making", "💎"), ("Pottery", "🏺"),
        ("Leather Working", "🧳"), ("Metal Working", "⚒️"), ("Welding", "🔥"),
        ("Home Renovation", "🏠"), ("Furniture Building", "🪑"), ("Painting Walls", "🖌️"),
        ("Tiling", "🧱"), ("Plumbing", "🔧"), ("Electrical Work", "⚡"),
        ("Upcycling", "♻️"), ("Decoupage", "🎨"), ("Paper Crafts", "📄"),
        ("Scrapbooking", "📒"), ("Card Making", "💌"), ("Stamping", "📬"),
        ("Sticker Making", "🏷️"), ("T-Shirt Printing", "👕"), ("Screen Printing", "🖨️"),
        ("Tie Dye", "🌈"), ("Macrame", "🪢"), ("Weaving", "🧶"),
        ("Basket Making", "🧺"), ("Rug Hooking", "🪝"), ("Felting", "🐑"),
        ("Glass Blowing", "🔥"), ("Stained Glass", "🪟"), ("Mosaic", "🧩"),
        ("Model Building", "🏗️"), ("Miniatures", "🪆"), ("Dollhouse", "🏠"),
        ("Diorama", "🏔️"), ("Cosplay Crafting", "🦸"), ("Prop Making", "🎭"),
        ("3D Printing", "🖨️"), ("CNC", "⚙️"), ("Laser Cutting", "💡"),
        ("Electronics DIY", "🔌"), ("Arduino", "🤖"), ("Raspberry Pi", "🍇"),
    ],
}


def seed_interests():
    """Seed the interests table if empty."""
    db = SessionLocal()
    try:
        existing = db.query(Interest).count()
        if existing > 0:
            return

        seen = set()
        count = 0
        for category, items in INTERESTS_BY_CATEGORY.items():
            for name, icon in items:
                if name in seen:
                    continue
                seen.add(name)
                db.add(Interest(name=name, category=category, icon=icon))
                count += 1
        db.commit()
        print(f"  Seeded {count} interests across {len(INTERESTS_BY_CATEGORY)} categories")
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_interests()
