import sys
import os

# Ensure the app module can be found
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.models import Post, User, Reaction, Comment
from app.services.bandit_service import rank_feed_with_bandit, W_SEMANTIC, W_BANDIT

# --- 1. MOCK DATA SETUP --- #

class MockPost:
    def __init__(self, id, content, ml_score, impression_count=0, click_count=0, likes=0, reactions=0, comments=0):
        self.id = id
        self.content = content
        self.ml_score = ml_score  # The base SVD projection
        self.impression_count = impression_count
        self.click_count = click_count
        
        # Mocking relationships
        self.liked_by = [User()] * likes
        self.reactions = [Reaction()] * reactions
        self.comments = [Comment()] * comments

# Simulate 5 posts generated by the overnight SVD Matrix Factorization pipeline.
# They are currently ranked exactly by ml_score.
print("\n" + "="*80)
print(" PHASE 1: OVERNIGHT SVD CANDIDATE RANKING (BEFORE BANDIT) ")
print("="*80)

simulated_posts = [
    # Highly relevant to user based on SVD, but community finds it boring (low engagement)
    MockPost(1, "Post A: Perfect ML Semantic Match, but boring", ml_score=0.98, impression_count=1000, likes=5, reactions=0, comments=0),
    
    # Decent semantic match, extremely controversial/conversational
    MockPost(2, "Post B: Decent ML Match, Highly Controversial", ml_score=0.75, impression_count=1000, likes=10, reactions=50, comments=120),
    
    # Good semantic match, well-liked
    MockPost(3, "Post C: Good Match, Very Popular", ml_score=0.85, impression_count=1000, likes=200, reactions=30, comments=10),
    
    # BRAND NEW POST: The ML thinks it's a weak match, but it has ZERO impressions.
    MockPost(4, "Post D: BRAND NEW POST (Cold Start)", ml_score=0.30, impression_count=0, likes=0, reactions=0, comments=0),
    
    # Weak ML match, terrible engagement
    MockPost(5, "Post E: Weak Match, No Engagement", ml_score=0.20, impression_count=1000, likes=1, reactions=0, comments=0),
]

# Print Before State
print(f"{'Post Content':<50} | {'ML (SVD) Score'}")
print("-" * 75)
for post in sorted(simulated_posts, key=lambda x: x.ml_score, reverse=True):
    print(f"{post.content:<50} | {post.ml_score:.4f}")

print("\n" + "="*80)
print(f" PHASE 2: REAL-TIME CONTEXTUAL BANDIT RANKING (AFTER BANDIT) ")
print(f" Anti-Dilution Blending parameters: {W_SEMANTIC*100}% SVD + {W_BANDIT*100}% RL ")
print("="*80)

# We package them into the tuple format the algorithm expects: (Post, ml_score)
candidates = [(post, post.ml_score) for post in simulated_posts]

# Run the real production Bandit logic!
ranked_posts = rank_feed_with_bandit(candidates)

print(f"{'Rank'} | {'Post Content':<50} | {'ML Score':<10} | {'Final Blended Score':<15}")
print("-" * 90)
import math
from app.services.bandit_service import calculate_post_ucb

# We recalculate total impressions just for display
total_impressions = sum(p.impression_count for p in simulated_posts)

for i, post in enumerate(ranked_posts):
    blended_score = calculate_post_ucb(post, post.ml_score, total_impressions)
    print(f"#{i+1:<3} | {post.content:<50} | {post.ml_score:<10.3f} | {blended_score:.4f}")

print("\n--- BANDIT LOGIC OBSERVATIONS ---")
print("1. [Cold Start Fixed]: Note how 'Post D' rocketed to the top! Because it had 0 impressions, the Bandit gave it an exploration bonus to test it.")
print("2. [Deep Engagement Fixed]: Note how 'Post B' beat 'Post A' and 'Post C'. Even though 'A' had the best ML score, 'B' had 120 comments, generating massive composite reward.")
print("3. [Semantic Protection]: 'Post C' generated good rewards, and combined with a solid ML score, it remains highly ranked. The ML wasn't diluted!")
print("="*80 + "\n")
